services:
  app-dev-server:
    image: node:18.14.0
    ports:
      - "8888:8888"
    volumes:
      - ..:/app-server
    working_dir: /app-server
    entrypoint: sh -c "yarn install && yarn build && yarn dev"
    environment:
      # explicitly override the value in the env file
      - DATABASE_HOST=${DATABASE_HOST}
  app-db-dev:
    container_name: app-db-dev
    image: postgres:15.4-alpine
    volumes: 
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  db:
    driver: local
